export const hrConstants = {
  REGISTER_REQUEST: 'HRS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'HRS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'HRS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'HRS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'HRS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'HRS_LOGIN_FAILURE',

  LOGOUT: 'HRS_LOGOUT',

  GETALL_REQUEST: 'HRS_GETALL_REQUEST',
  GETALL_SUCCESS: 'HRS_GETALL_SUCCESS',
  GETALL_FAILURE: 'HRS_GETALL_FAILURE',

  DELETE_REQUEST: 'HRS_DELETE_REQUEST',
  DELETE_SUCCESS: 'HRS_DELETE_SUCCESS',
  DELETE_FAILURE: 'HRS_DELETE_FAILURE'
};

export const CREATE_HR = 'CREATE_HR';
export const RETRIEVE_HRS = 'RETRIEVE_HRS';
export const UPDATE_HR = 'UPDATE_HR';
export const DELETE_HR = 'DELETE_HR';
export const DELETE_ALL_HRS = 'DELETE_ALL_HRS';
export const COUNT_CHANGE = 'COUNTER_CHANGE';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};

export const alertConstants = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR'
};
